consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  Todo:
    description: Todos (default view)
    example:
      body: hoge
      id: 1
      is_finished: false
    properties:
      body:
        description: body
        example: hoge
        type: string
      id:
        description: id
        example: 1
        format: int64
        type: integer
      is_finished:
        description: is_finished
        example: false
        type: boolean
    required:
    - id
    - body
    - is_finished
    title: 'Mediatype identifier: application/todo.+json; view=default'
    type: object
  TodoCollection:
    description: TodoCollection is the media type for an array of Todo (default view)
    example:
    - body: hoge
      id: 1
      is_finished: false
    - body: hoge
      id: 1
      is_finished: false
    - body: hoge
      id: 1
      is_finished: false
    items:
      $ref: '#/definitions/Todo'
    title: 'Mediatype identifier: application/todo.+json; type=collection; view=default'
    type: array
  error:
    description: Error response media type (default view)
    example:
      code: invalid_value
      detail: Value of ID must be an integer
      id: 3F1FKVRR
      meta:
        timestamp: 1.458609e+09
      status: "400"
    properties:
      code:
        description: an application-specific error code, expressed as a string value.
        example: invalid_value
        type: string
      detail:
        description: a human-readable explanation specific to this occurrence of the
          problem.
        example: Value of ID must be an integer
        type: string
      id:
        description: a unique identifier for this particular occurrence of the problem.
        example: 3F1FKVRR
        type: string
      meta:
        additionalProperties: true
        description: a meta object containing non-standard meta-information about
          the error.
        example:
          timestamp: 1.458609e+09
        type: object
      status:
        description: the HTTP status code applicable to this problem, expressed as
          a string value.
        example: "400"
        type: string
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
host: localhost:8080
info:
  description: Treasure mid
  title: todoz
  version: ""
paths:
  /todos/:
    delete:
      description: Todoの全削除
      operationId: todos#delete all
      produces:
      - application/vnd.goa.error
      - application/todo.+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Todo'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: delete all todos
      tags:
      - todos
    get:
      description: TodoList一覧
      operationId: todos#list
      produces:
      - application/vnd.goa.error
      - application/todo.+json; type=collection
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/TodoCollection'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: list todos
      tags:
      - todos
    post:
      description: Todoの作成
      operationId: todos#create
      parameters:
      - description: body
        in: query
        name: body
        required: true
        type: string
      produces:
      - application/vnd.goa.error
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: create todos
      tags:
      - todos
  /todos/{id}:
    delete:
      description: Todoの削除
      operationId: todos#delete
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/vnd.goa.error
      - application/todo.+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Todo'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "404":
          description: Not Found
      schemes:
      - http
      summary: delete todos
      tags:
      - todos
    get:
      description: Todoの詳細
      operationId: todos#show
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/vnd.goa.error
      - application/todo.+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Todo'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "404":
          description: Not Found
      schemes:
      - http
      summary: show todos
      tags:
      - todos
    put:
      description: Todoの更新
      operationId: todos#update
      parameters:
      - description: body
        in: query
        name: body
        required: true
        type: string
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: is_finished
        in: query
        name: is_finished
        required: true
        type: boolean
      produces:
      - application/vnd.goa.error
      - application/todo.+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Todo'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "404":
          description: Not Found
      schemes:
      - http
      summary: update todos
      tags:
      - todos
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
responses:
  Created:
    description: Created
  NotFound:
    description: Not Found
  OK:
    description: OK
    schema:
      $ref: '#/definitions/Todo'
schemes:
- http
swagger: "2.0"
