// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "todoz": Application User Types
//
// Command:
// $ goagen
// --design=github.com/konchanSS/Todoz/design
// --out=$(GOPATH)/src/github.com/konchanSS/Todoz
// --version=v1.2.0-dirty

package app
